project_id = "wjlkvqswgaylrmrwedqd"

[functions.send-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.resend-otp]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.change-email]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false
