project_id = "wjlkvqswgaylrmrwedqd"

[functions.send-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.login]
verify_jwt = false