project_id = "wjlkvqswgaylrmrwedqd"

[functions.upload-profile-picture]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.resend-otp]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.change-email]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.get-roles]
verify_jwt = false

[functions.manage-role]
verify_jwt = false

[functions.get-permissions]
verify_jwt = false

[functions.update-permissions]
verify_jwt = false

[functions.assign-user-role]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.toggle-user-status]
verify_jwt = false
